---
title: "Exercise 4"
author: "Sonali Mishra"
date: "05/01/2022"
output:
  md_document:
    variant: markdown_github
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = TRUE)
# installs the librarian package if you don't have it
if (!("librarian" %in% rownames(utils::installed.packages()))) {
  utils::install.packages("librarian")
}

# put all of the packages that you import here
librarian::shelf( 
  cran_repo = "https://cran.microsoft.com/", # Dallas, TX
  ask = FALSE,
  stats, # https://stackoverflow.com/questions/26935095/r-dplyr-filter-not-masking-base-filter#answer-26935536
  here,
  kableExtra,
  rlang,
  ggthemes,
  tidyverse,
  janitor,
  magrittr,
  glue,
  lubridate,
  haven,
  snakecase,
  sandwich,
  lmtest,
  gganimate,
  gapminder,
  stargazer,
  snakecase,
  rpart,
  rpart.plot,
  rsample,
  randomForest,
  modelr,
  gbm,
  pdp,
  remotes,
  urbnmapr,
  ggmap,
  maps,
  mapdata,
  usmap,
  scales,
  foreach,
  caret,
  mosaic,
  LICORS,
  ggcorrplot,
  arules,
  arulesViz,
  igraph,
  RColorBrewer
)

# tell here where we are so we can use it elsewhere
here::i_am("Data-Mining-PS4/include.R")
```

##Clustering and PCA

```{r}

wine = read_csv(here("Data-Mining-PS4/Clustering and PCA/wine.csv"))
wine = na.omit(wine)
view(wine)
#centre, scaling and rescaling
X = wine[, -(12:13)]
X = scale(X, center=TRUE, scale=TRUE)
mu = attr(X,"scaled:center")
sigma = attr(X,"scaled:scale")

#kmeans for wine comparision 
kmeans_cluster_wine = kmeans(X, 2, nstart=25)

ggplot(wine) + 
  geom_point(aes(color, density, color=factor(kmeans_cluster_wine$cluster)))+
  xlab("Color of the wine in original data") +
  ylab("Density") +
  labs(color = "Kmeans clustering")

#kmeans for quality comparison
kmeans_cluster_quality = kmeans(X, 10, nstart=25)

ggplot(wine) + 
  geom_point(aes(quality, density, color=factor(kmeans_cluster_quality$cluster)))+
  xlab("Quality of the wine in original data") +
  ylab("Density") +
  labs(color = "Kmeans clustering")

#kmeans++ for wine comparison
kmeanspp_cluster_wine = kmeanspp(X, 2, nstart=25)

ggplot(wine) + 
  geom_point(aes(color, density, color=factor(kmeanspp_cluster_wine$cluster)))+
  xlab("Color of the wine in original data") +
  ylab("Density") +
  labs(color = "Kmeans++ clustering")

#kmeans++ for quality comparison
kmeanspp_cluster_quality = kmeanspp(X, 10, nstart=25)

ggplot(wine) + 
  geom_point(aes(quality, density, color=factor(kmeanspp_cluster_quality$cluster)))+
  xlab("Quality of the wine in original data") +
  ylab("Density") +
  labs(color = "Kmeans++ clustering")

#tabular representation
df = data.frame(
  kmeanserr = c(kmeans_cluster_wine$tot.withinss,kmeans_cluster_wine$betweenss,kmeans_cluster_quality$tot.withinss,kmeans_cluster_quality$betweenss),
  kmeanspperr = c(kmeanspp_cluster_wine$tot.withinss,kmeanspp_cluster_wine$betweenss,kmeanspp_cluster_quality$tot.withinss,kmeanspp_cluster_quality$betweenss)
)
colnames(df) = c("Kmeans", "Kmeans++")
rownames(df) = c("within cluster error for wine","between cluster error for wine","within cluster error for quality","between cluster error for quality")

df = df %>%
  kbl() %>%
  kable_material_dark()
df

#agglomerative hierarchial clustering
wine_dist = dist(X)
#for wine
h1_wine = hclust(wine_dist, method='average')
c1_wine = cutree(h1_wine, 2)
D1_wine = data.frame(wine, z1_wine = c1_wine)
ggplot(D1_wine) + geom_point(aes(x=color, y=density, col=factor(z1_wine)))

h2_wine = hclust(wine_dist, method='average')
c2_wine = cutree(h2_wine, 2)
D2_wine = data.frame(wine, z2_wine = c2_wine)
ggplot(D2_wine) + geom_point(aes(x=color, y=density, col=factor(z2_wine)))

h3_wine = hclust(wine_dist, method='average')
c3_wine = cutree(h3_wine, 2)
D3_wine = data.frame(wine, z3_wine = c3_wine)
ggplot(D3_wine) + geom_point(aes(x=color, y=density, col=factor(z3_wine)))

#for quality 
h1_quality = hclust(wine_dist, method='average')
c1_quality = cutree(h1_quality, 10)
D1_quality = data.frame(wine, z1_quality = c1_quality)
ggplot(D1_quality) + geom_point(aes(x=color, y=density, col=factor(z1_quality)))


h2_quality = hclust(wine_dist, method='average')
c2_quality = cutree(h2_quality, 10)
D2_quality = data.frame(wine, z2_quality = c2_quality)
ggplot(D2_quality) + geom_point(aes(x=color, y=density, col=factor(z2_quality)))


h3_quality = hclust(wine_dist, method='average')
c3_quality = cutree(h3_quality, 10)
D3_quality = data.frame(wine, z3_quality = c3_quality)
ggplot(D3_quality) + geom_point(aes(x=color, y=density, col=factor(z3_quality)))


#PCA
pc1 = prcomp(X, scale=TRUE, rank=2)
loadings = pc1$rotation
scores = pc1$x

qplot(scores[,1], scores[,2], color=wine$color, xlab='PCA1', ylab='PCA2')

head(pc1$rotation)
summary(pc1)

```

